image: registry.gitlab.tugraz.at/dbp/web-components/dbp-starter-app/main:v1

cache:
  key: $CI_PROJECT_PATH
  paths:
    - _yarn_cache

before_script:
  - "sed -i 's|git@gitlab.tugraz.at:dbp|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init
  - yarn config set cache-folder "$CI_PROJECT_DIR/_yarn_cache"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn run build
    - yarn run test-full

linting:
  stage: test
  allow_failure: true
  script:
    - yarn install
    - yarn run lint